language: r

sudo: required

warnings_are_errors: true

env: R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
 - jimhester/covr
 - hadley/testthat

after_success:
 - Rscript -e 'devtools::install()'
 - Rscript -e 'devtools::session_info()'
 - env: COVR=true
 - Rscript -e 'library(covr); coveralls(quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
