language: r
sudo: false
cache: packages
r:
  - oldrel # when oldrel = 3.1, there are S3 method problems I can't debug
  - release
  - devel

os:
  - linux
  - osx

warnings_are_errors: true

r_github_packages:
 - jimhester/covr
 - hadley/testthat

after_success:
 - Rscript -e 'devtools::install()'
 - Rscript -e 'devtools::session_info()'
 - Rscript -e 'library(covr); coveralls(quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
