language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

os:
  - linux

warnings_are_errors: true

r_github_packages:
 - jimhester/covr

after_success:
 - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
