language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

os:
  - linux

warnings_are_errors: true

r_github_packages:
 - covr

after_success:
 - Rscript -e 'covr::coveralls()'
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
