language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
  - r: oldrel
  - os: osx

env:
  global:
    - R_CHECK_CRAN_INCOMING_=FALSE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: true

r_binary_install:
 - knitr
 - testthat

r_install:
 - lintr
 - Rcpp

install_github:
 - r-lib/covr

after_success:
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
