language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

os:
  - linux

warnings_are_errors: true

after_success:
 - Rscript -e 'devtools::install()'
 - Rscript -e 'devtools::session_info()'
 - Rscript -e 'covr::coveralls()'
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
