// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// isRowSorted
LogicalVector isRowSorted(NumericMatrix x);
RcppExport SEXP jwutil_isRowSorted(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(isRowSorted(x));
    return __result;
END_RCPP
}
// propRowSorted
double propRowSorted(NumericMatrix x);
RcppExport SEXP jwutil_propRowSorted(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(propRowSorted(x));
    return __result;
END_RCPP
}
