# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

start_profiler <- function(x) {
    .Call('jwutil_start_profiler', PACKAGE = 'jwutil', x)
}

stop_profiler <- function() {
    .Call('jwutil_stop_profiler', PACKAGE = 'jwutil')
}

#' @name stressprof
#' @title stressprof
#' @param x matrix, each row containing ordered or disordered numerics
#' @export
#' @import Rcpp
stressprof <- function(x) {
    .Call('jwutil_stressprof', PACKAGE = 'jwutil', x)
}

#' @name isRowSorted
#' @title is every row sorted?
#' @description Quicky run through rows of a matrix looking for any
#' non-ascending rows in C++
#' @param x matrix, each row containing ordered or disordered numerics
#' @export
#' @import Rcpp
isRowSorted <- function(x) {
    .Call('jwutil_isRowSorted', PACKAGE = 'jwutil', x)
}

#' @name propRowSorted
#' @title proportion of non-descending rows in matrix
#' @description first performs isRowSorted to get a logical vector,
#' then sums TRUE values and takes fraction of total
#' @param x matrix, each row containing ordered or disordered numerics
#' @return double, the proportion from 0 to 1
#' @export
#' @import Rcpp
propRowSorted <- function(x) {
    .Call('jwutil_propRowSorted', PACKAGE = 'jwutil', x)
}

